# Configuration file for Snakemake workflow
# Each section corresponds to a rule in the Snakemake file

# Centralized file paths and parameters
collected_papers: "path/to/your/HEA_electrocatalyst.csv"
processed_papers: "path/to/your/HEA_electrocatalyst_processed_df.csv"


# Parameters for collecting papers
rule_collect_papers:
  # Path to the configuration file for ScopusDataSource
  config_path: "pybliometrics.cfg"
  # Keywords for the paper query
  keywords: "'electrocatalyst' OR 'high entropy alloy'"
  # Start year for the paper query, or "" for no start year
  startyear: 2022
  # End year for the paper query
  endyear: 2024
  # Whether to search for open access papers
  openaccess: true

# Configuration for pybliometrics.cfg, which will be created/updated if it doesn't exist
#Full content for pybliometrics.cfg
pybliometrics_config:
  Directories:
    AbstractRetrieval: "path/to/your/pybliometrics/Scopus/abstract_retrieval"
    AffiliationRetrieval: "path/to/your/pybliometrics/affiliation_retrieval"
    AffiliationSearch: "path/to/your/pybliometrics/affiliation_search"
    AuthorRetrieval: "path/to/your/pybliometrics/author_retrieval"
    AuthorSearch: "path/to/your/pybliometrics/author_search"
    CitationOverview: "path/to/your/pybliometrics/citation_overview"
    ScopusSearch: "path/to/your/pybliometrics/scopus_search"
    SerialSearch: "path/to/your/pybliometrics/serial_search"
    SerialTitle: "path/to/your/pybliometrics/serial_title"
    PlumXMetrics: "path/to/your/pybliometrics/plumx"
    SubjectClassifications: "path/to/your/pybliometrics/subject_classification"

  Authentication:
    APIKey:
      - '5cc854f28c6d5bf6573fe065317aafdf'
      # Add more API keys as needed

  Requests:
    Timeout: 36000
    Retries: 2

# Parameters for generating word2vec model
rule_generate_word2vec:
  # Output path for the generated word2vec model
  model_path: "path/to/your/HEA_electrocatalyst.model"
  # Training algorithm: 1 for skip-gram, 0 for CBOW
  sg: 1
  # Dimensionality of the word vectors
  vector_size: 200
  # If 1, hierarchical softmax will be used for model training
  hs: 1
  # Maximum distance between the current and predicted word within a sentence
  window: 5
  # Ignores all words with total frequency lower than this
  min_count: 1
  # Number of worker threads to train the model
  workers: 4
