# Centralized file paths and parameters (for paths used in multiple rules)

# Data for publication from
# Banko, L., Krysiak, O., Schumann, W., & Ludwig, A. (2024).
# Electrochemical activity of several compositions in the system Ag-Pd-Pt-Ru for the oxygen reduction reaction in 0.05 M KOH solution pH 12.5 [Data set].
# Zenodo. https://doi.org/10.5281/zenodo.13992986

Ag_Pd_Ru: "/path/to/your/Ag_Pd_Ru.csv"
Ag_Pd_Pt: "/path/to/your/Ag_Pd_Pt.csv"
Ag_Pd_Pt_Ru: "/path/to/your/Ag_Pd_Pt_Ru.csv"

HEA_model: "../word2vec_model/HEA_electrocatalyst.model"

prediction_gpy: "../prediction_models/Ag_Pd_Pt_Ru_with_predictions_Gpy.csv"
prediction_gpy_embedding: "../prediction_models/Ag_Pd_Pt_Ru_with_predictions_Gpy_with_embedding.csv"
prediction_standard_vec: "../prediction_models/Ag_Pd_Pt_Ru_with_predictions_Standard_Vec.csv"

# Configuration for Visualizing Material Vectors
rule_visualize_material_vectors:
  # Output path for the generated plot PDF
  output_path: "property_best_electrocatalysts_vectors.pdf"
  # List of materials to visualize
  material_list:
    - "Ru0Pd0.86Ag0.14"
    - "Pd0.3Ag0.31Pt0.39"
    - "Ru0.14Pd0.23Ag0.09Pt0.53"
  # List of properties to include in the visualization
  property_list:
    - "electrocatalyst"
    - "overpotential"
    - "tafel slope"
    - "exchange current density"
    - "stability"
    - "durability"
    - "surface area"
    - "active site"
    - "turnover frequency"
    - "electrocatalytic activity"
    - "faradaic efficiency"
    - "charge transfer"
    - "adsorption energy"
    - "electronic structure"
    - "electronegativity"
    - "crystal structure"
    - "surface morphology"
  # Visualization parameters
  marker_size: 25
  axisfont_size: 25
  tickfont_size: 20
  width: 2800
  height: 1400
  show_legend: false
  textfont_size: 25

# Configuration for ElementConcentrationPlotter

rule_generate_element_concentration_plot:
  # Output path for the plot PDF file
  output: "element_concentration_horizontal_range_plot.pdf"

# Configuration for plotting current density at 850mV

rule_plot_current_density:
  # Names of the systems corresponding to the data files
  system_names:
    - "Ag-Pd-Ru"
    - "Ag-Pd-Pt"
    - "Ag-Pd-Pt-Ru"
  # Output path for the plot PDF
  output_path: "current_density_horizontal_range_plot.pdf"

# Configuration for plotting stacked step histogram

rule_plot_stacked_step_histogram:
  # Names of the systems corresponding to the data files
  system_names:
    - "Ag-Pd-Ru"
    - "Ag-Pd-Pt"
    - "Ag-Pd-Pt-Ru"
  # Output path for the plot PDF
  output_path: "current_density_stacked_step_histogram.pdf"
  # Number of bins for the histogram
  bins: 10
  # Column name for the data to be plotted
  column_name: "Current_at_850mV"

# Configuration for "Ag_Pd_Ru_dataset_elements.pdf"

rule_plot_Ag_Pd_Ru_dataset_elements:
  elements:
    - "data1:Ag,Pd,Ru"
  x_labels: ["Ag", "Pd", "Ru"]
  y_labels: ["Ag", "Pd", "Ru"]
  output_path: "path/to/your/Ag_Pd_Ru_dataset_elements.pdf"
  ncols: 3
  nrows: 1
  subplot_labels: false

# Configuration for "ternary_datasets_current.pdf"

rule_plot_ternary_datasets_current:
  elements:
    - "data1:Current_at_850mV"
    - "data2:Current_at_850mV"
  x_labels: ["Current_at_850mV"]
  y_labels: ["Current_at_850mV"]
  legend_labels: "{\"mA/cm²\": [\"Current_at_850mV\"]}"
  cmap_groups: "{\"plasma\": [\"Current_at_850mV\"]}"
  output_path: "ternary_datasets_current.pdf"
  ncols: 2
  nrows: 1
  subplot_labels: true

# Configuration for "Ag_Pd_Pt_dataset_elements.pdf"

rule_plot_Ag_Pd_Pt_dataset_elements:
  elements:
    - "data1:Ag,Pd,Pt"
  x_labels: ["Ag", "Pd", "Pt"]
  y_labels: ["Ag", "Pd", "Pt"]
  output_path: "Ag_Pd_Pt_dataset_elements.pdf"
  ncols: 3
  nrows: 1
  subplot_labels: false

# Configuration for "Ag_Pd_Pt_Ru_dataset_elements.pdf"

rule_plot_Ag_Pd_Pt_Ru_dataset_elements:
  elements:
    - "data1:Ag,Pd,Pt,Ru"
  x_labels: ["Ag", "Pd", "Pt", "Ru"]
  y_labels: ["Ag", "Pd", "Pt", "Ru"]
  output_path: "Ag_Pd_Pt_Ru_dataset_elements.pdf"
  ncols: 2
  nrows: 2
  subplot_labels: false

# Configuration for "quaternary_current_with_predictions.pdf"

rule_plot_quaternary_current_with_predictions:
  elements:
    - "data1:Current_at_850mV,Predicted_Value"
    - "data2:Predicted_Value"
    - "data3:Similarity"
  x_labels: ["Current_at_850mV", "Predicted_Value", "Similarity"]
  y_labels: ["Current_at_850mV", "Predicted_Value", "Similarity"]
  legend_labels: "{\"mA/cm²\": [\"Current_at_850mV\", \"Predicted_Value\"]}"
  cmap_groups: "{\"plasma\": [\"Current_at_850mV\", \"Predicted_Value\", \"Similarity\"]}"
  output_path: "quaternary_current_with_predictions.pdf"
  ncols: 2
  nrows: 2
  subplot_labels: true

# Configuration for plotting correlation with optional filtering and fit line

rule_plot_correlation:
  # List of names corresponding to each dataset
  names:
    - "Gpy_Model"
    - "Gpy_Embedding_Enhanced_Model"
    - "Standard_Vec_Model"
  # Name of the column for the X-axis
  x_col: "Current_at_850mV"
  # Name of the column for the Y-axis
  y_col: "Predicted_Value"
  # Combined plot or separate plots
  combined: True  # Use Python-style True
  # Show fit line on the plots
  show_fit_line: True  # Use Python-style True
  # Optional filter for the data (e.g., "Current_at_850mV < -0.2" or "" for no filter)
  filter: ""
  # Output file path for saving the plot
  output_file: "correlation_plot.pdf"

# Configuration for plotting integrated density plot
rule_integrated_density_plot:
  # List of column names to be used for color-coding each file
  columns:
    - 'Current_at_850mV'
    - 'Current_at_850mV'
    - 'Predicted_Value'
    - 'Predicted_Value'
    - 'Similarity'
  # Plot types for each file (either 'xy' for a regular plot or 'x_only' for a combined x plot)
  plot_types:
    - 'xy'
    - 'x_only'
    - 'x_only'
    - 'x_only'
    - 'x_only'
  # Custom legend labels for x_only plots
  legend_labels:
    - "\"Experimental\""
    - "\"Model 1\""
    - "\"Model 2\""
    - "\"Model 3\""
  # Font size for all text elements
  fontsize: 16
  # Width of each subplot in inches
  subplot_width: 7
  # Height of each subplot in inches
  subplot_height: 5
  # Path to save the output PDF
  output_file: "IntegratedDensityCombinedXPlot.pdf"
